"""
Audit endpoints.

POST /audits                    — start a new audit
GET  /audits/{id}/stream        — SSE stream of live turns
GET  /audits/{id}/turns         — polling fallback: all turns + verdicts
GET  /audits/{id}/debrief       — completed debrief card
"""

import asyncio
import json
import logging
import threading
import uuid

from fastapi import APIRouter, HTTPException, Depends, Request
from sse_starlette.sse import EventSourceResponse

from app.api.dependencies import get_session_id
from app.constants import ROUND_TOPICS
from app.database import get_supabase
from app.models.schemas import (
    AuditCreateRequest,
    AuditCreateResponse,
    TurnsListResponse,
    TurnResponse,
    VerdictResponse,
    DebriefCardResponse,
    ErrorResponse,
)
from app.agents.graph import run_audit

logger = logging.getLogger(__name__)
router = APIRouter(tags=["audits"])

# ---------------------------------------------------------------------------
# In-process concurrency: one audit at a time to respect Gemini rate limits.
# ---------------------------------------------------------------------------
_audit_lock = threading.Lock()

# Active SSE queues, keyed by audit_id.
# Each value is an asyncio.Queue that the graph pushes events onto.
_sse_queues: dict[str, asyncio.Queue] = {}

# Reference to the main event loop (set during app lifespan).
_event_loop: asyncio.AbstractEventLoop | None = None


def set_event_loop(loop: asyncio.AbstractEventLoop) -> None:
    """Called once from main.py lifespan to capture the loop reference."""
    global _event_loop
    _event_loop = loop


# ---------------------------------------------------------------------------
# POST /audits
# ---------------------------------------------------------------------------
@router.post(
    "/audits",
    response_model=AuditCreateResponse,
    responses={400: {"model": ErrorResponse}},
)
async def create_audit(
    body: AuditCreateRequest,
    session_id: str = Depends(get_session_id),
):
    """Start a new audit for a paper + round topic."""
    # Validate topic
    if body.round_topic not in ROUND_TOPICS:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid round_topic '{body.round_topic}'. "
            f"Must be one of: {list(ROUND_TOPICS.keys())}",
        )

    # Verify paper exists
    supabase = get_supabase()
    paper = supabase.table("papers").select("id").eq("id", body.paper_id).execute()
    if not paper.data:
        raise HTTPException(status_code=404, detail="Paper not found")

    # Create audit + round rows
    audit_id = str(uuid.uuid4())
    round_id = str(uuid.uuid4())

    supabase.table("audits").insert({
        "id": audit_id,
        "paper_id": body.paper_id,
        "session_id": session_id,
        "round_topic": body.round_topic,
        "strictness_level": "standard",
        "depth": "fast",
        "status": "in_progress",
    }).execute()

    supabase.table("rounds").insert({
        "id": round_id,
        "audit_id": audit_id,
        "round_number": 1,
        "topic": body.round_topic,
        "status": "in_progress",
    }).execute()

    # Set up SSE queue
    queue: asyncio.Queue = asyncio.Queue()
    _sse_queues[audit_id] = queue

    # Create the SSE callback that pushes events from the graph thread
    # into the asyncio queue (thread-safe).
    loop = _event_loop or asyncio.get_event_loop()

    def sse_callback(event: dict) -> None:
        loop.call_soon_threadsafe(queue.put_nowait, event)

    # Launch the graph in a background thread.
    def _run():
        with _audit_lock:
            try:
                run_audit(body.paper_id, round_id, body.round_topic, sse_callback)
            except Exception as exc:
                logger.exception("Audit %s failed: %s", audit_id, exc)
            finally:
                # Signal stream completion
                loop.call_soon_threadsafe(queue.put_nowait, None)

    thread = threading.Thread(target=_run, daemon=True)
    thread.start()

    logger.info("Audit %s started (topic: %s)", audit_id, body.round_topic)

    return AuditCreateResponse(
        audit_id=audit_id,
        round_id=round_id,
        status="in_progress",
    )


# ---------------------------------------------------------------------------
# GET /audits/{audit_id}/stream — SSE
# ---------------------------------------------------------------------------
@router.get("/audits/{audit_id}/stream")
async def stream_audit(audit_id: str, request: Request):
    """
    Server-Sent Events stream of turns, verdicts, and the debrief card
    as they are generated by the agent graph.
    """
    queue = _sse_queues.get(audit_id)
    if queue is None:
        # Audit might already be done — check DB status
        supabase = get_supabase()
        audit = supabase.table("audits").select("status").eq("id", audit_id).execute()
        if not audit.data:
            raise HTTPException(status_code=404, detail="Audit not found")
        if audit.data[0]["status"] == "completed":
            raise HTTPException(
                status_code=410,
                detail="Audit already completed. Use /turns and /debrief instead.",
            )
        raise HTTPException(status_code=404, detail="SSE stream not available")

    async def event_generator():
        try:
            while True:
                # Check if client disconnected
                if await request.is_disconnected():
                    break

                try:
                    event = await asyncio.wait_for(queue.get(), timeout=30)
                except asyncio.TimeoutError:
                    # Send heartbeat to keep connection alive
                    yield {"event": "heartbeat", "data": "{}"}
                    continue

                if event is None:
                    # Stream complete
                    yield {"event": "complete", "data": "{}"}
                    break

                event_type = event.get("type", "message")
                event_data = json.dumps(event.get("data", {}))
                yield {"event": event_type, "data": event_data}

        finally:
            # Clean up the queue
            _sse_queues.pop(audit_id, None)

    return EventSourceResponse(event_generator())


# ---------------------------------------------------------------------------
# GET /audits/{audit_id}/turns — polling fallback
# ---------------------------------------------------------------------------
@router.get(
    "/audits/{audit_id}/turns",
    response_model=TurnsListResponse,
)
async def list_turns(audit_id: str):
    """
    Polling fallback — returns all turns and verdicts so far.
    Used when the SSE connection drops.
    """
    supabase = get_supabase()

    # Get audit
    audit = supabase.table("audits").select("status").eq("id", audit_id).execute()
    if not audit.data:
        raise HTTPException(status_code=404, detail="Audit not found")

    # Get round(s) for this audit
    rounds = supabase.table("rounds").select("id").eq("audit_id", audit_id).execute()
    if not rounds.data:
        return TurnsListResponse(turns=[], verdicts=[], status=audit.data[0]["status"])

    round_ids = [r["id"] for r in rounds.data]

    # Get all turns
    turns_data = (
        supabase.table("turns")
        .select("*")
        .in_("round_id", round_ids)
        .order("exchange_number")
        .order("sequence")
        .execute()
    )

    # Get all verdicts
    verdicts_data = (
        supabase.table("verdicts")
        .select("*")
        .in_("round_id", round_ids)
        .order("exchange_number")
        .execute()
    )

    turns = []
    for t in (turns_data.data or []):
        content = t["content"]
        if isinstance(content, str):
            try:
                content = json.loads(content)
            except (json.JSONDecodeError, TypeError):
                pass
        turns.append(TurnResponse(
            id=t["id"],
            exchange_number=t["exchange_number"],
            agent_type=t["agent_type"],
            sequence=t["sequence"],
            content=content,
            created_at=t.get("created_at", ""),
        ))

    verdicts = []
    for v in (verdicts_data.data or []):
        cited = v.get("cited_chunk_ids")
        if isinstance(cited, str):
            try:
                cited = json.loads(cited)
            except (json.JSONDecodeError, TypeError):
                pass
        verdicts.append(VerdictResponse(
            id=v["id"],
            exchange_number=v["exchange_number"],
            claim_summary=v.get("claim_summary"),
            verdict_type=v["verdict_type"],
            confidence=v.get("confidence"),
            rationale=v.get("rationale"),
            cited_chunk_ids=cited,
        ))

    return TurnsListResponse(
        turns=turns,
        verdicts=verdicts,
        status=audit.data[0]["status"],
    )


# ---------------------------------------------------------------------------
# GET /audits/{audit_id}/debrief
# ---------------------------------------------------------------------------
@router.get(
    "/audits/{audit_id}/debrief",
    response_model=DebriefCardResponse,
    responses={404: {"model": ErrorResponse}},
)
async def get_debrief(audit_id: str):
    """Return the completed Debrief Card, or 404 if not yet generated."""
    supabase = get_supabase()

    # Get round for this audit
    rounds = supabase.table("rounds").select("id").eq("audit_id", audit_id).execute()
    if not rounds.data:
        raise HTTPException(status_code=404, detail="No round found for this audit")

    round_id = rounds.data[0]["id"]

    debrief = (
        supabase.table("debrief_cards")
        .select("*")
        .eq("round_id", round_id)
        .execute()
    )

    if not debrief.data:
        raise HTTPException(
            status_code=404,
            detail="Debrief card not yet generated — audit may still be in progress.",
        )

    d = debrief.data[0]

    # Parse JSON fields if stored as strings
    for field in ("solidified_strengths", "actionable_weaknesses", "contested_points"):
        val = d.get(field)
        if isinstance(val, str):
            try:
                d[field] = json.loads(val)
            except (json.JSONDecodeError, TypeError):
                d[field] = []

    # Fetch paper_id and topic to attach reproducibility_checklist if relevant
    reproducibility_checklist = None
    try:
        audit_res = supabase.table("audits").select("paper_id, round_topic").eq("id", audit_id).execute()
        if audit_res.data:
            paper_id = audit_res.data[0].get("paper_id")
            topic = audit_res.data[0].get("round_topic")
            if topic == "reproducibility" and paper_id:
                paper_res = supabase.table("papers").select("reproducibility_signals").eq("id", paper_id).execute()
                if paper_res.data and paper_res.data[0].get("reproducibility_signals"):
                    reproducibility_checklist = paper_res.data[0]["reproducibility_signals"]
    except Exception as exc:
        logger.warning("Could not fetch reproducibility checklist for debrief: %s", exc)

    return DebriefCardResponse(
        id=d["id"],
        executive_synthesis=d.get("executive_synthesis"),
        solidified_strengths=d.get("solidified_strengths"),
        actionable_weaknesses=d.get("actionable_weaknesses"),
        contested_points=d.get("contested_points"),
        reproducibility_checklist=reproducibility_checklist,
    )

